"""Retrieval primitives for Helix Support Intelligence."""

from helix_support_intelligence.retrieval.core import (
    BM25Retriever,
    BootstrapInterval,
    DenseRetriever,
    Document,
    EligibilityPolicy,
    EmbeddingEncoder,
    LatencySummary,
    PairScorer,
    RankedDocument,
    candidate_earns_complexity,
    document_from_record,
    filter_eligible_documents,
    is_eligible,
    macro_average,
    mrr_at_k,
    ndcg_at_k,
    paired_bootstrap_difference,
    recall_at_k,
    reciprocal_rank_fusion,
    rerank_top,
    summarize_latency,
    tokenize,
)
from helix_support_intelligence.retrieval.evaluation import (
    AggregateMetrics,
    QueryMetrics,
    aggregate_metrics,
    evaluate_ranking,
)
from helix_support_intelligence.retrieval.ladder import CandidateId, RetrievalLadder

__all__ = [
    "AggregateMetrics",
    "BM25Retriever",
    "BootstrapInterval",
    "CandidateId",
    "DenseRetriever",
    "Document",
    "EligibilityPolicy",
    "EmbeddingEncoder",
    "LatencySummary",
    "PairScorer",
    "QueryMetrics",
    "RankedDocument",
    "RetrievalLadder",
    "aggregate_metrics",
    "candidate_earns_complexity",
    "document_from_record",
    "evaluate_ranking",
    "filter_eligible_documents",
    "is_eligible",
    "macro_average",
    "mrr_at_k",
    "ndcg_at_k",
    "paired_bootstrap_difference",
    "recall_at_k",
    "reciprocal_rank_fusion",
    "rerank_top",
    "summarize_latency",
    "tokenize",
]
